### ISSUE TITLE
Question: General Information Storage

### ISSUE THREAD

**Issue by jmhobbs** [sdmp/sdmp.github.io#6]
In the [general information](http://sdmp.github.io/docs/resources/#general-information) section of the resources page, it states:

```
For general visible content, the sdmp object in the resource’s 
YAML document has the following reserved properties:

sdmp.document (object)
```

However, in the [examples](http://sdmp.github.io/docs/resources/#examples), there is a public blog post where the general public data is defined in the main YAML body, instead of in `sdmp.document`

``` yaml

---
sdmp:
    version: 0.9
    publisher: 7a5179eecc0fe18760ba615f92603372ae3fe302860098a019e15927551fee3b
    created: 2015-04-23
blog:
    author:
        name: John Doe
        hash: 7a5179eecc0fe18760ba615f92603372ae3fe302860098a019e15927551fee3b
    data: |
        This is an imagined *markdown* formatted thing, like a blog post or whatnot.
...
```

Is this a valid document?  Is placing the content on `sdmp.document` optional?

**Comment by saibotsivad** [comment]
Oh my, I forgot to update the examples! I'll get on that Monday night.

On June 22, 2015 12:48:26 AM CDT, John Hobbs notifications@github.com wrote:

> In the [general
> information](http://sdmp.github.io/docs/resources/#general-information)
> section of the resources page, it states:
> 
> ```
> For general visible content, the sdmp object in the resource’s 
> YAML document has the following reserved properties:
> 
> sdmp.document (object)
> ```
> 
> However, in the
> [http://sdmp.github.io/docs/resources/#examples](examples), there is a
> public blog post where the general public data is defined in the main
> YAML body, instead of in `sdmp.document`
> 
> ``` yaml
> ---
> sdmp:
>   version: 0.9
>   publisher:
> 7a5179eecc0fe18760ba615f92603372ae3fe302860098a019e15927551fee3b
>   created: 2015-04-23
> blog:
>   author:
>       name: John Doe
>       hash:
> 7a5179eecc0fe18760ba615f92603372ae3fe302860098a019e15927551fee3b
>   data: |
>       This is an imagined *markdown* formatted thing, like a blog post or
> whatnot.
> ...
> ```
> 
> Is this a valid document?  Is placing the content on `sdmp.document`
> optional?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sdmp/sdmp.github.io/issues/6

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jmhobbs** [comment]
So it should be under sdmp then?  Just checking.

``` yaml
---
sdmp:
    version: 0.9
    publisher: 7a5179eecc0fe18760ba615f92603372ae3fe302860098a019e15927551fee3b
    created: 2015-04-23
    document:
        blog:
            author:
                name: John Doe
                hash: 7a5179eecc0fe18760ba615f92603372ae3fe302860098a019e15927551fee3b
            data: |
                This is an imagined *markdown* formatted thing, like a blog post or whatnot.
...
```

If thats the case I'd be happy to update the examples and do a PR
